<script setup>
import { computed, onMounted, ref } from 'vue'
import { DeleteTAOrderById, GetUserTAOrderList } from '@/api/home/tourist.js'
import { useUserinfo } from '@/components/Avatar/hooks/useUserinfo.js'
import { Delete } from '@element-plus/icons-vue'
import { ElMessage, ElMessageBox } from 'element-plus'

const pageParams = ref({
  page: 1,
  limit: 8
})
const total = ref(0)
const list = ref()
const user = ref()
onMounted(async () => {
  const { userinfo } = useUserinfo()
  user.value = userinfo.value
  await fetchData()
})
const fetchData = async () => {
  const { data } = await GetUserTAOrderList(
    pageParams.value.page,
    pageParams.value.limit,
    user.value.id
  )
  list.value = data.records
  total.value = data.total
  //处理照片url
  list.value.forEach(item => {
    if (item.photoUrls !== '' && item.photoUrls != null) {
      item.photoUrls = item.photoUrls.split(',')
    }
  })
}
const deleteOrder = async id => {
  ElMessageBox.confirm('此操作将永久删除该订单记录, 是否继续?', 'Warning', {
    confirmButtonText: '确定',
    cancelButtonText: '取消',
    type: 'warning'
  }).then(async () => {
    const { code } = await DeleteTAOrderById(id)
    if (code === 200) {
      ElMessage.success('删除成功')
      await fetchData()
    } else {
      ElMessage.error('删除失败')
    }
  })
}
const backgroundImageUrl = props => {
  // 判断 photoUrls 是否存在且有至少一张图片
  if (props.photoUrls && props.photoUrls.length > 0) {
    // 返回第一张图片的 URL
    return props.photoUrls[0]
  } else {
    // 返回默认的背景图片 URL
    return '默认背景图片 URL'
  }
}
</script>

<template>
  <div class="list">
    <div
      class="one"
      v-for="item in list"
      :key="item.id"
      :style="{ backgroundImage: 'url(' + backgroundImageUrl(item) + ')' }"
    >
      <div class="name">{{ item.tname }}</div>
      <div class="time">有效期&nbsp;{{ item.validityTime }}</div>
      <div class="price">￥{{ item.totalAmount }}</div>
      <!-- 隐藏盒子     -->
      <div class="textBox">
        <el-button @click="deleteOrder(item.id)">
          <el-icon>
            <Delete />
          </el-icon>
        </el-button>
        <div class="originPrice">原价：￥{{ item.originalTotalAmount }}</div>
        <div>优惠：￥0</div>
        <div class="payType">
          支付方式：
          <span v-if="item.payType === 1" style="color: #1CD66C">微信支付</span
          ><span v-if="item.payType === 2" style="color: #409EFF"
            >支付宝支付</span
          >
        </div>
        <div class="payTime">支付时间：{{ item.paymentTime }}</div>
      </div>
    </div>
  </div>
  <div class="bottom">
    <el-pagination
      v-model:current-page="pageParams.page"
      v-model:page-size="pageParams.limit"
      :page-sizes="[10, 20, 50, 100]"
      @size-change="fetchData"
      @current-change="fetchData"
      layout="total, sizes, prev, pager, next"
      :total="total"
    />
  </div>
</template>

<style scoped lang="scss">
.list {
  width: 100%;
  padding: 0 10px;
  box-sizing: border-box;
  display: flex;
  flex-wrap: wrap;

  .one {
    overflow: hidden;
    background-size: cover;
    background-color: rgba(247, 207, 5, 0.23);
    cursor: pointer;
    border: 2px solid #eee;
    box-sizing: border-box;
    border-radius: 5px;
    padding: 20px 15px;
    height: 360px;
    position: relative;
    width: calc(25% - 30px); /* 计算每个项目的宽度，留出一些空间 */
    margin: 15px; /* 项目之间的间距 */
    .name {
      color: white;
      width: 100%;
      overflow: hidden;
      text-overflow: ellipsis;
      flex-wrap: nowrap;
      font-size: 39px;
      text-shadow: 2px 2px 10px rgba(0, 0, 0, 0.5);
    }

    .time {
      color: whitesmoke;
      font-size: 17px;
      text-shadow: 2px 2px 10px rgba(0, 0, 0, 0.5);
    }

    .price {
      text-shadow: 2px 2px 10px rgba(0, 0, 0, 0.5);
      font-size: 23px;
      color: white;
      position: absolute;
      bottom: 20px;
      right: 20px;
    }

    .textBox {
      box-sizing: border-box;
      position: absolute;
      bottom: 0;
      left: 0;
      width: 100%;
      height: 45%;
      font-size: 18px;
      color: #5c5c5c;
      background-color: rgba(255, 255, 255, 0.97);
      opacity: 0; /* 默认隐藏 */
      padding: 10px 12px;

      .el-button {
        float: right;
        background-color: transparent;
        border: none;
        width: 20px;
        height: 30px;
      }
    }

    .originPrice,
    .payType,
    .payTime {
      margin-bottom: 5px;
    }
  }

  .one:hover {
    .textBox {
      opacity: 1;
      animation: slide-in-bottom 0.5s cubic-bezier(0.25, 0.46, 0.45, 0.94) both;
    }
  }
}

/* ----------------------------------------------
 * Generated by Animista on 2024-4-11 16:54:18
 * Licensed under FreeBSD License.
 * See http://animista.net/license for more info.
 * w: http://animista.net, t: @cssanimista
 * ---------------------------------------------- */

/**
 * ----------------------------------------
 * animation slide-in-bottom
 * ----------------------------------------
 */
@-webkit-keyframes slide-in-bottom {
  0% {
    -webkit-transform: translateY(1000px);
    transform: translateY(1000px);
    opacity: 0;
  }
  100% {
    -webkit-transform: translateY(0);
    transform: translateY(0);
    opacity: 1;
  }
}

@keyframes slide-in-bottom {
  0% {
    -webkit-transform: translateY(1000px);
    transform: translateY(1000px);
    opacity: 0;
  }
  100% {
    -webkit-transform: translateY(0);
    transform: translateY(0);
    opacity: 1;
  }
}
</style>
